#!/usr/bin/env python3
"""
Display Autocorrelation Plot
Loads and displays the autocorrelation_analysis.png image generated by autocorrelation_analysis.py.
"""

import matplotlib.pyplot as plt
import matplotlib.image as mpimg

def display_autocorrelation_plot():
    """Load and display the autocorrelation plot image"""
    try:
        # Load the image
        img = mpimg.imread('autocorrelation_analysis.png')

        # Create a new figure
        plt.figure(figsize=(15, 6))

        # Display the image
        plt.imshow(img)
        plt.axis('off')  # Hide axes for cleaner display
        plt.title('Volatility Autocorrelation for SPY and BTC-USD')

        # Show the plot inline
        plt.show()

        print("Autocorrelation plot displayed successfully")
    except FileNotFoundError:
        print("Error: 'autocorrelation_analysis.png' not found. Please run autocorrelation_analysis.py first.")
    except Exception as e:
        print(f"Error displaying plot: {e}")

if __name__ == "__main__":
    # Ensure matplotlib inline for Jupyter environments
    try:
        # This line is only effective in Jupyter notebooks
        %matplotlib inline
    except:
        pass  # Ignore if not in Jupyter

    display_autocorrelation_plot()
